resource_types:
  - name: pull-request
    type: registry-image
    source:
      repository: teliaoss/github-pr-resource
  - name: gcs
    type: registry-image
    source:
      repository: frodenas/gcs-resource

resources:
  - name: gpdb6
    type: git
    source:
      uri: https://github.com/greenplum-db/gpdb.git
      branch: 6X_STABLE

  - name: gpdb5
    type: git
    source:
      uri: https://github.com/greenplum-db/gpdb.git
      branch: 5X_STABLE

  - name: gpdb6-pull-request
    type: pull-request
    source:
      repository: greenplum-db/gpdb
      access_token: ((gpdb-git-access-token))
      base_branch: "6X_STABLE"
      ignore_paths:
        - gpdb-doc/*
        - README*

jobs:
  - name: end-to-end-test
    plan:
      - aggregate:
        - get: gpdb6
          trigger: true
        - get: gpdb5
          trigger: true
      - task: run-test
        file: gpdb6/contrib/pg_upgrade/ci/run-test.yml
        timeout: 1h

  - name: pull-request-end-to-end-test
    plan:
      - aggregate:
        - get: gpdb6
          resource: gpdb6-pull-request
          trigger: true
        - get: gpdb5
      - task: run-test
        file: gpdb6/contrib/pg_upgrade/ci/run-test.yml
        timeout: 1h
